
//自动生成
using Framework;
using UnityEngine;
using UnityEngine.UI;
public partial class SelectRoleUI
{
	private UnityEngine.UI.Button changeAction_Button;
	private UnityEngine.UI.Button carBtn_Button;
	private UnityEngine.UI.Button roleBtn_Button;
	private TMPro.TextMeshProUGUI nickName_TextMeshProUGUI;
	private UnityEngine.UI.Button giftBtn_Button;
	private UnityEngine.UI.Button rankBtn_Button;
	private UnityEngine.UI.Image changeIcon_Image;
	private UnityEngine.UI.Button changeIcon_Button;
	private UnityEngine.UI.Button trophyBtn_Button;
	private TMPro.TextMeshProUGUI item1Count_TextMeshProUGUI;
	private UnityEngine.UI.Button stake_Button;
	private UnityEngine.UI.Button item1add_Button;
	private UnityEngine.UI.Button shop_Button;
	private TMPro.TextMeshProUGUI item0Count_TextMeshProUGUI;
	private UnityEngine.UI.Button item0add_Button;
	private UnityEngine.RectTransform item0Icon_RectTransform;
	private UnityEngine.RectTransform rankBtn_RectTransform;
	private UnityEngine.RectTransform flyTarget1_RectTransform;
	private TMPro.TextMeshProUGUI upgradeTip_TextMeshProUGUI;
	private UnityEngine.GameObject lvup_GameObject;
	private UnityEngine.UI.Button race_Button;
	private UnityEngine.UI.Button okx_Button;
	private UnityEngine.UI.Button change_Button;
	private TMPro.TextMeshProUGUI item2Count_TextMeshProUGUI;
	private UnityEngine.UI.Button item2add_Button;
	private TMPro.TextMeshProUGUI item2info1_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI item2info2_TextMeshProUGUI;
	private UnityEngine.UI.Button turntable_Button;
	private TMPro.TextMeshProUGUI turntabletime_TextMeshProUGUI;
	private UnityEngine.UI.Button pvp_Button;
	private UnityEngine.UI.Button pve_Button;
	private UnityEngine.UI.Button assets_Button;
	private UnityEngine.UI.Button garage_Button;
	private UnityEngine.UI.Button shequ_Button;
	private UnityEngine.UI.Button saishi_Button;
	private UnityEngine.UI.Button yugao_Button;
	private UnityEngine.UI.Button kmoney_Button;
	private UnityEngine.UI.Button paihang_Button;
	private TMPro.TextMeshProUGUI pvpstate_TextMeshProUGUI;
	private UnityEngine.UI.Button invite_Button;

    protected override void InjectFields(GameObjectFields value)
    {
		this.changeAction_Button = (UnityEngine.UI.Button)value.FieldItems[0].Value;
		this.carBtn_Button = (UnityEngine.UI.Button)value.FieldItems[1].Value;
		this.roleBtn_Button = (UnityEngine.UI.Button)value.FieldItems[2].Value;
		this.nickName_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[3].Value;
		this.giftBtn_Button = (UnityEngine.UI.Button)value.FieldItems[4].Value;
		this.rankBtn_Button = (UnityEngine.UI.Button)value.FieldItems[5].Value;
		this.changeIcon_Image = (UnityEngine.UI.Image)value.FieldItems[6].Value;
		this.changeIcon_Button = (UnityEngine.UI.Button)value.FieldItems[7].Value;
		this.trophyBtn_Button = (UnityEngine.UI.Button)value.FieldItems[8].Value;
		this.item1Count_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[9].Value;
		this.stake_Button = (UnityEngine.UI.Button)value.FieldItems[10].Value;
		this.item1add_Button = (UnityEngine.UI.Button)value.FieldItems[11].Value;
		this.shop_Button = (UnityEngine.UI.Button)value.FieldItems[12].Value;
		this.item0Count_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[13].Value;
		this.item0add_Button = (UnityEngine.UI.Button)value.FieldItems[14].Value;
		this.item0Icon_RectTransform = (UnityEngine.RectTransform)value.FieldItems[15].Value;
		this.rankBtn_RectTransform = (UnityEngine.RectTransform)value.FieldItems[16].Value;
		this.flyTarget1_RectTransform = (UnityEngine.RectTransform)value.FieldItems[17].Value;
		this.upgradeTip_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[18].Value;
		this.lvup_GameObject = (UnityEngine.GameObject)value.FieldItems[19].Value;
		this.race_Button = (UnityEngine.UI.Button)value.FieldItems[20].Value;
		this.okx_Button = (UnityEngine.UI.Button)value.FieldItems[21].Value;
		this.change_Button = (UnityEngine.UI.Button)value.FieldItems[22].Value;
		this.item2Count_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[23].Value;
		this.item2add_Button = (UnityEngine.UI.Button)value.FieldItems[24].Value;
		this.item2info1_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[25].Value;
		this.item2info2_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[26].Value;
		this.turntable_Button = (UnityEngine.UI.Button)value.FieldItems[27].Value;
		this.turntabletime_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[28].Value;
		this.pvp_Button = (UnityEngine.UI.Button)value.FieldItems[29].Value;
		this.pve_Button = (UnityEngine.UI.Button)value.FieldItems[30].Value;
		this.assets_Button = (UnityEngine.UI.Button)value.FieldItems[31].Value;
		this.garage_Button = (UnityEngine.UI.Button)value.FieldItems[32].Value;
		this.shequ_Button = (UnityEngine.UI.Button)value.FieldItems[33].Value;
		this.saishi_Button = (UnityEngine.UI.Button)value.FieldItems[34].Value;
		this.yugao_Button = (UnityEngine.UI.Button)value.FieldItems[35].Value;
		this.kmoney_Button = (UnityEngine.UI.Button)value.FieldItems[36].Value;
		this.paihang_Button = (UnityEngine.UI.Button)value.FieldItems[37].Value;
		this.pvpstate_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[38].Value;
		this.invite_Button = (UnityEngine.UI.Button)value.FieldItems[39].Value;
		this.changeAction_Button.onClick.AddListener(() => { this.OnButtonClick(this.changeAction_Button); });
		this.carBtn_Button.onClick.AddListener(() => { this.OnButtonClick(this.carBtn_Button); });
		this.roleBtn_Button.onClick.AddListener(() => { this.OnButtonClick(this.roleBtn_Button); });
		this.giftBtn_Button.onClick.AddListener(() => { this.OnButtonClick(this.giftBtn_Button); });
		this.rankBtn_Button.onClick.AddListener(() => { this.OnButtonClick(this.rankBtn_Button); });
		this.changeIcon_Button.onClick.AddListener(() => { this.OnButtonClick(this.changeIcon_Button); });
		this.trophyBtn_Button.onClick.AddListener(() => { this.OnButtonClick(this.trophyBtn_Button); });
		this.stake_Button.onClick.AddListener(() => { this.OnButtonClick(this.stake_Button); });
		this.item1add_Button.onClick.AddListener(() => { this.OnButtonClick(this.item1add_Button); });
		this.shop_Button.onClick.AddListener(() => { this.OnButtonClick(this.shop_Button); });
		this.item0add_Button.onClick.AddListener(() => { this.OnButtonClick(this.item0add_Button); });
		this.race_Button.onClick.AddListener(() => { this.OnButtonClick(this.race_Button); });
		this.okx_Button.onClick.AddListener(() => { this.OnButtonClick(this.okx_Button); });
		this.change_Button.onClick.AddListener(() => { this.OnButtonClick(this.change_Button); });
		this.item2add_Button.onClick.AddListener(() => { this.OnButtonClick(this.item2add_Button); });
		this.turntable_Button.onClick.AddListener(() => { this.OnButtonClick(this.turntable_Button); });
		this.pvp_Button.onClick.AddListener(() => { this.OnButtonClick(this.pvp_Button); });
		this.pve_Button.onClick.AddListener(() => { this.OnButtonClick(this.pve_Button); });
		this.assets_Button.onClick.AddListener(() => { this.OnButtonClick(this.assets_Button); });
		this.garage_Button.onClick.AddListener(() => { this.OnButtonClick(this.garage_Button); });
		this.shequ_Button.onClick.AddListener(() => { this.OnButtonClick(this.shequ_Button); });
		this.saishi_Button.onClick.AddListener(() => { this.OnButtonClick(this.saishi_Button); });
		this.yugao_Button.onClick.AddListener(() => { this.OnButtonClick(this.yugao_Button); });
		this.kmoney_Button.onClick.AddListener(() => { this.OnButtonClick(this.kmoney_Button); });
		this.paihang_Button.onClick.AddListener(() => { this.OnButtonClick(this.paihang_Button); });
		this.invite_Button.onClick.AddListener(() => { this.OnButtonClick(this.invite_Button); });

    }
}
