
//自动生成
using Framework;
using UnityEngine;
using UnityEngine.UI;
public partial class StakeUI
{
	private UnityEngine.UI.Button close_Button;
	private UnityEngine.UI.Button moneyStart_Button;
	private UnityEngine.UI.Button carStart_Button;
	private UnityEngine.GameObject carnode_GameObject;
	private TMPro.TextMeshProUGUI needlv_TextMeshProUGUI;
	private UnityEngine.UI.Button carStake_Button;
	private UnityEngine.UI.Button carNodeClose_Button;
	private UnityEngine.GameObject moneynode_GameObject;
	private UnityEngine.UI.Button moneyNodeClose_Button;
	private UnityEngine.UI.Button moneyStake_Button;
	private UnityEngine.UI.Slider money_Slider;
	private TMPro.TextMeshProUGUI showmoney_TextMeshProUGUI;
	private UnityEngine.UI.Button moneyCancel_Button;
	private UnityEngine.UI.Button moneyClaim_Button;
	private UnityEngine.UI.Button carClaim_Button;
	private TMPro.TextMeshProUGUI carlv_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carClaimCd_TextMeshProUGUI;
	private UnityEngine.UI.Button carReplace_Button;
	private TMPro.TextMeshProUGUI carvalue_TextMeshProUGUI;
	private UnityEngine.GameObject carclaimNode_GameObject;
	private TMPro.TextMeshProUGUI cartotalstake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carcount_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carstake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carreceived_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carunclaim_TextMeshProUGUI;
	private UnityEngine.UI.Button moneyadd_Button;
	private UnityEngine.UI.Button moneysub_Button;
	private UnityEngine.GameObject moneyclaimNode_GameObject;
	private TMPro.TextMeshProUGUI moneytotalstake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneystake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneyreceived_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneyunclaim_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI totalstake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI totalday_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI stakeEndTime_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneyClaimCd_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneycount_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI carcountValue_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneycountValue_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI cartodaytotalstake_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI moneytodaytotalstake_TextMeshProUGUI;
	private UnityEngine.UI.Button moneyRedeemCancel_Button;
	private UnityEngine.UI.Button moneyRedeemOk_Button;
	private UnityEngine.GameObject redeemnode_GameObject;
	private TMPro.TextMeshProUGUI carLv1_TextMeshProUGUI;
	private UnityEngine.UI.Button carRedeemOk_Button;
	private UnityEngine.UI.Button carRedeemCancel_Button;
	private UnityEngine.GameObject carCancelnode_GameObject;
	private TMPro.TextMeshProUGUI allValue_TextMeshProUGUI;
	private TMPro.TextMeshProUGUI ranktxt_TextMeshProUGUI;
	private UnityEngine.UI.Button rankIcon_Button;
	private UnityEngine.RectTransform rankIcon_RectTransform;
	private UnityEngine.RectTransform carTimeImg_RectTransform;
	private UnityEngine.RectTransform moneyTimeImg_RectTransform;
	private UnityEngine.UI.Button rankclick_Button;
	private UnityEngine.UI.Button rule_Button;

    protected override void InjectFields(GameObjectFields value)
    {
		this.close_Button = (UnityEngine.UI.Button)value.FieldItems[0].Value;
		this.moneyStart_Button = (UnityEngine.UI.Button)value.FieldItems[1].Value;
		this.carStart_Button = (UnityEngine.UI.Button)value.FieldItems[2].Value;
		this.carnode_GameObject = (UnityEngine.GameObject)value.FieldItems[3].Value;
		this.needlv_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[4].Value;
		this.carStake_Button = (UnityEngine.UI.Button)value.FieldItems[5].Value;
		this.carNodeClose_Button = (UnityEngine.UI.Button)value.FieldItems[6].Value;
		this.moneynode_GameObject = (UnityEngine.GameObject)value.FieldItems[7].Value;
		this.moneyNodeClose_Button = (UnityEngine.UI.Button)value.FieldItems[8].Value;
		this.moneyStake_Button = (UnityEngine.UI.Button)value.FieldItems[9].Value;
		this.money_Slider = (UnityEngine.UI.Slider)value.FieldItems[10].Value;
		this.showmoney_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[11].Value;
		this.moneyCancel_Button = (UnityEngine.UI.Button)value.FieldItems[12].Value;
		this.moneyClaim_Button = (UnityEngine.UI.Button)value.FieldItems[13].Value;
		this.carClaim_Button = (UnityEngine.UI.Button)value.FieldItems[14].Value;
		this.carlv_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[15].Value;
		this.carClaimCd_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[16].Value;
		this.carReplace_Button = (UnityEngine.UI.Button)value.FieldItems[17].Value;
		this.carvalue_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[18].Value;
		this.carclaimNode_GameObject = (UnityEngine.GameObject)value.FieldItems[19].Value;
		this.cartotalstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[20].Value;
		this.carcount_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[21].Value;
		this.carstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[22].Value;
		this.carreceived_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[23].Value;
		this.carunclaim_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[24].Value;
		this.moneyadd_Button = (UnityEngine.UI.Button)value.FieldItems[25].Value;
		this.moneysub_Button = (UnityEngine.UI.Button)value.FieldItems[26].Value;
		this.moneyclaimNode_GameObject = (UnityEngine.GameObject)value.FieldItems[27].Value;
		this.moneytotalstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[28].Value;
		this.moneystake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[29].Value;
		this.moneyreceived_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[30].Value;
		this.moneyunclaim_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[31].Value;
		this.totalstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[32].Value;
		this.totalday_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[33].Value;
		this.stakeEndTime_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[34].Value;
		this.moneyClaimCd_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[35].Value;
		this.moneycount_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[36].Value;
		this.carcountValue_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[37].Value;
		this.moneycountValue_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[38].Value;
		this.cartodaytotalstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[39].Value;
		this.moneytodaytotalstake_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[40].Value;
		this.moneyRedeemCancel_Button = (UnityEngine.UI.Button)value.FieldItems[41].Value;
		this.moneyRedeemOk_Button = (UnityEngine.UI.Button)value.FieldItems[42].Value;
		this.redeemnode_GameObject = (UnityEngine.GameObject)value.FieldItems[43].Value;
		this.carLv1_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[44].Value;
		this.carRedeemOk_Button = (UnityEngine.UI.Button)value.FieldItems[45].Value;
		this.carRedeemCancel_Button = (UnityEngine.UI.Button)value.FieldItems[46].Value;
		this.carCancelnode_GameObject = (UnityEngine.GameObject)value.FieldItems[47].Value;
		this.allValue_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[48].Value;
		this.ranktxt_TextMeshProUGUI = (TMPro.TextMeshProUGUI)value.FieldItems[49].Value;
		this.rankIcon_Button = (UnityEngine.UI.Button)value.FieldItems[50].Value;
		this.rankIcon_RectTransform = (UnityEngine.RectTransform)value.FieldItems[51].Value;
		this.carTimeImg_RectTransform = (UnityEngine.RectTransform)value.FieldItems[52].Value;
		this.moneyTimeImg_RectTransform = (UnityEngine.RectTransform)value.FieldItems[53].Value;
		this.rankclick_Button = (UnityEngine.UI.Button)value.FieldItems[54].Value;
		this.rule_Button = (UnityEngine.UI.Button)value.FieldItems[55].Value;
		this.close_Button.onClick.AddListener(() => { this.OnButtonClick(this.close_Button); });
		this.moneyStart_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyStart_Button); });
		this.carStart_Button.onClick.AddListener(() => { this.OnButtonClick(this.carStart_Button); });
		this.carStake_Button.onClick.AddListener(() => { this.OnButtonClick(this.carStake_Button); });
		this.carNodeClose_Button.onClick.AddListener(() => { this.OnButtonClick(this.carNodeClose_Button); });
		this.moneyNodeClose_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyNodeClose_Button); });
		this.moneyStake_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyStake_Button); });
		this.moneyCancel_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyCancel_Button); });
		this.moneyClaim_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyClaim_Button); });
		this.carClaim_Button.onClick.AddListener(() => { this.OnButtonClick(this.carClaim_Button); });
		this.carReplace_Button.onClick.AddListener(() => { this.OnButtonClick(this.carReplace_Button); });
		this.moneyadd_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyadd_Button); });
		this.moneysub_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneysub_Button); });
		this.moneyRedeemCancel_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyRedeemCancel_Button); });
		this.moneyRedeemOk_Button.onClick.AddListener(() => { this.OnButtonClick(this.moneyRedeemOk_Button); });
		this.carRedeemOk_Button.onClick.AddListener(() => { this.OnButtonClick(this.carRedeemOk_Button); });
		this.carRedeemCancel_Button.onClick.AddListener(() => { this.OnButtonClick(this.carRedeemCancel_Button); });
		this.rankIcon_Button.onClick.AddListener(() => { this.OnButtonClick(this.rankIcon_Button); });
		this.rankclick_Button.onClick.AddListener(() => { this.OnButtonClick(this.rankclick_Button); });
		this.rule_Button.onClick.AddListener(() => { this.OnButtonClick(this.rule_Button); });

    }
}
