// <auto-generated>
//  automatically generated by IDataTableProcessor, do not modify
// </auto-generated>
using Framework.DataTable;
using Framework;
public partial class TableManager : DataTableManager
{
	public Car_Table Car { get; private set; }
	public CarModules_Table CarModules { get; private set; }
	public CarUpgrade_Table CarUpgrade { get; private set; }
	public Gift_Table Gift { get; private set; }
	public GiftRandom_Table GiftRandom { get; private set; }
	public Head_Table Head { get; private set; }
	public Item_Table Item { get; private set; }
	public Lang_Table Lang { get; private set; }
	public LuckyBox_Table LuckyBox { get; private set; }
	public LuckyTurntable_Table LuckyTurntable { get; private set; }
	public Map_Table Map { get; private set; }
	public MapStar_Table MapStar { get; private set; }
	public Mining_Table Mining { get; private set; }
	public Nickname_Table Nickname { get; private set; }
	public Param_Table Param { get; private set; }
	public RankTiers_Table RankTiers { get; private set; }
	public Role_Table Role { get; private set; }
	public Room_Table Room { get; private set; }
	public SeasonJourney_Table SeasonJourney { get; private set; }
	public Shop_Table Shop { get; private set; }
	public Task_Table Task { get; private set; }
	public TreasureChest_Table TreasureChest { get; private set; }

    public TableManager()
    {
		Car = add(new Car_Table());
		CarModules = add(new CarModules_Table());
		CarUpgrade = add(new CarUpgrade_Table());
		Gift = add(new Gift_Table());
		GiftRandom = add(new GiftRandom_Table());
		Head = add(new Head_Table());
		Item = add(new Item_Table());
		Lang = add(new Lang_Table());
		LuckyBox = add(new LuckyBox_Table());
		LuckyTurntable = add(new LuckyTurntable_Table());
		Map = add(new Map_Table());
		MapStar = add(new MapStar_Table());
		Mining = add(new Mining_Table());
		Nickname = add(new Nickname_Table());
		Param = add(new Param_Table());
		RankTiers = add(new RankTiers_Table());
		Role = add(new Role_Table());
		Room = add(new Room_Table());
		SeasonJourney = add(new SeasonJourney_Table());
		Shop = add(new Shop_Table());
		Task = add(new Task_Table());
		TreasureChest = add(new TreasureChest_Table());

    }
}